print("jujur adalah dari untuk kunci keberhasilan")
print("cita cita aku adalah ingin menjadi spidermen")
print("jangan merokok")
print("hobby aku bermain game")
print("makanan favorit aku gado gado")
print("warna favorit aku hijau")
print("aku adalah ultramen")
print("aku adalah bocil kematian")
print("aku ingin menguasai dunia")
print("jangan lupa tidur")